version: '3'

services:
#  app:
#    build: .
#    ports:
#      - '80:80'
#    links:
#      - 'db:carrinho'
#    restart: always
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_DATABASE: 'carrinho'
      MYSQL_USER: 'carrinho_admin'
      MYSQL_PASSWORD: '0^GI^kz4!gEH41O^71UyyoxKwxlm'
    ports:
      - '3306:3306'